### ISSUE TITLE
emulator won't start due to using qemu_i386

### ISSUE THREAD

**Issue by neofreko** [agoda-com/docker-emulator-android#5]
It looks like emulator won't start when adb is renamed to _adb

![image](https://user-images.githubusercontent.com/8678/46845583-ff24bc00-ce16-11e8-94c9-cf0448835cec.png)

Dismissing the error won't resume emulator booting sequence.
There's a setting to provide custom adb path, but it won't accept `_adb`.

Due to this issue, emulator never comes online in the android-farm.

**Comment by neofreko** [comment]
Digging up further, it looks like the same issue posted here: https://issuetracker.google.com/issues/37047668#c10

**Comment by neofreko** [comment]
Turned out switching to `qemu_x68_64` solve this issue. It takes a couple of minutes. But it boots. Compare this against running the image with `qemu_i386` which never complete the boot.

The missing adb part probably is not an issue in regard to booting.

**Comment by Malinskiy** [comment]
@neofreko This is the correct behavior: it is advised to use separate container with adb server so that you don't bundle the adb server into the emulator container.
The x64 version is a bit slower than i386 in our experience, but if it solves your use case then why not use it.
